#!/usr/bin/python3

import logging
import sys

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)
logger.addHandler(logging.StreamHandler())
logging.basicConfig(format='%(asctime)s 123 %(levelname)s abcd %(name)s: %(message)s')

def ok_shutdown():
    logger.info("Initiating shutdown.")
    sys.exit(0)

def ko_shutdown():
    logger.error("Bad Karma")
    sys.exit(1)


def insert_warning():
    logger.warning("This is not a wanring")

if __name__ == '__main__':
    logger.info('Fake odoo started')
    logger.info('Command line args: {}'.format(sys.argv[1:]))
    logger.info('.modules.loading: Modules loaded.')
    insert_warning()
    ko_shutdown()
